# Generated by Django 2.2.16 on 2022-03-03 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentPost',
        ),
    ]
